### ISSUE TITLE
Better reference checking support

### ISSUE THREAD

**Issue by wosledon** [tooltitude/support-pb#2]
Now the plugin can jump by reference, but it can't check if the reference exists, which is a big problem for me when working with protobuf files.

**Comment by tooltitude-support** [comment]
@wosledon For now, the main reason we didn't implement it is that we don't have access to the "standard" library. If you are aware of its standard location, we could add it, and check references (we have all required code to check for unresolved references).

**Comment by tooltitude-support** [comment]
@wosledon We added support to specify the "standard" library. See https://github.com/tooltitude/support-pb/issues/3

Will think about how we could add checking in a useable way without disrupting users too much.

**Comment by tooltitude-support** [comment]
@wosledon The extension now has an automatic discovery of standard library, so we decided to introduce settings for reference checking. We have two of them now: tooltitude.pb.refsCheckEnabled, and tooltitude.pb.importsCheckEnabled. Please, enable them, and see how it handles your use case.

The change is available in 0.18.0 which should be out very soon. Please, reopen the issue, if you have any problems with it. (Also, feel free to write comments, if you have any thoughts about the features).
