### ISSUE TITLE
Option to add paths for analysis

### ISSUE THREAD

**Issue by Real-Gecko** [tooltitude/support-pb#3]
OS Version: Arch Linux

VS Code Version: 1.94.2

Go Version: 1.23.2

Code Repository (if open source):

Feature request:
Adding paths for extra analysis would be nice, for example
```proto
import "google/protobuf/timestamp.proto";

message SomeMessage {
    optional google.protobuf.Timestamp created = 1;
    optional google.protobuf.Timestamp modified = 2;
}
```
Google proto files are located in `/usr/include` however language server does not know that, so no autocompletion suggestions etc.

**Comment by tooltitude-support** [comment]
@Real-Gecko Are you sure that they are /usr/include? If they are there, we could add handling of them.

**Comment by Real-Gecko** [comment]
> @Real-Gecko Are you sure that they are /usr/include? If they are there, we could add handling of them.

They definitely are.

![image](https://github.com/user-attachments/assets/eea69a15-48d2-46e0-9e96-02ae55b9e262)

**Comment by tooltitude-support** [comment]
@Real-Gecko Thanks for looking. These are great news!

**Comment by tooltitude-support** [comment]
@Real-Gecko Thanks for looking. This is really great!

**Comment by tooltitude-support** [comment]
@Real-Gecko Interestingly, on my machine there's no protobuf dir in the include. How did you install it? (I installed via homebrew for linux)

**Comment by tooltitude-support** [comment]
@Real-Gecko Ok. Homebrew puts them in /home/linuxbrew/.linuxbrew/include/google/protobuf It's a bit different, but still there.

**Comment by Real-Gecko** [comment]
> @Real-Gecko Interestingly, on my machine there's no protobuf dir in the include. How did you install it? (I installed via homebrew for linux)

They're part of `protobuf` package in Arch https://archlinux.org/packages/extra/x86_64/protobuf/

> @Real-Gecko Ok. Homebrew puts them in /home/linuxbrew/.linuxbrew/include/google/protobuf It's a bit different, but still there.

I use `--proto_path=/usr/include` parameter during compilation with `protoc` to make 'em discoverable.
This extension can use some kind of `Extra include directories` in same fashion for extra include discovery like `python` extension does (see for `extraPaths` https://code.visualstudio.com/docs/python/settings-reference.

**Comment by tooltitude-support** [comment]
@Real-Gecko I want to make the system discover everything automatically, but if the parameter has to be specified explicitly, probably providing option is the best bet.

**Comment by tooltitude-support** [comment]
@Real-Gecko Ok. Added the tooltitude.pb.includes setting. For example, you could add it via:

```
    "tooltitude.pb.includes": [
        "/home/linuxbrew/.linuxbrew/include/google/protobuf"
    ]
```

I started the build for a new version (0.17.0). It should be available in 10-20 minutes. Please let me know if it works for you. If it doesn't work, please reply and reopen the issue.

**Comment by Real-Gecko** [comment]
> @Real-Gecko Ok. Added the tooltitude.pb.includes setting. For example, you could add it via:
> 
> ```
>     "tooltitude.pb.includes": [
>         "/home/linuxbrew/.linuxbrew/include/google/protobuf"
>     ]
> ```
> 
> I started the build for a new version (0.17.0). It should be available in 10-20 minutes. Please let me know if it works for you. If it doesn't work, please reply and reopen the issue.

It works! Thanks for your help, really appreciated!
